---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    containerImage: quay.io/openshift/origin-aws-ebs-csi-driver-operator:latest
    categories: "Storage"
    capabilities: Basic Install
    description: |-
      Operator to install and maintain the AWS EBS CSI Driver on a cluster.
    certified: "false"
    support: https://github.com/openshift/aws-ebs-csi-driver-operator
    repository: https://github.com/openshift/aws-ebs-csi-driver-operator
    createdAt: 2020-03-24:13:08:00
    olm.skipRange: '>=4.3.0 <4.5.0'
    alm-examples: |-
      [
        {
          "apiVersion": "ebs.aws.csi.openshift.io/v1alpha1",
          "kind": "Driver",
          "metadata": {
            "name": "cluster"
          },
          "spec": {
            "managementState": "Managed"
          }
        }
      ]
  name: aws-ebs-csi-driver-operator.v4.5.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  maturity: alpha
  version: 4.5.0
  minKubeVersion: 1.17.0
  description: |-
     Operator to install and maintain the AWS EBS CSI Driver on a cluster.
  displayName: AWS EBS CSI Operator
  keywords: ['aws', 'CSI']
  maintainers:
  - name: Red Hat
    email: aos-storage-staff@redhat.com
  provider:
    name: Red Hat
  labels:
    alm-owner-metering: aws-ebs-csi-driver-operator
    alm-status-descriptors: aws-ebs-csi-driver-operator.v4.5.0
  selector:
    matchLabels:
      alm-owner-metering: aws-ebs-csi-driver-operator
  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: true
  - type: MultiNamespace
    supported: false
  - type: AllNamespaces
    supported: true
  install:
    strategy: deployment
    spec:
      permissions:
      - serviceAccountName: aws-ebs-csi-driver-operator
        rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
      clusterPermissions:
      - serviceAccountName: aws-ebs-csi-driver-operator
        rules:
        - apiGroups:
          - "security.openshift.io"
          resources:
          - securitycontextconstraints
          verbs:
          - use
          resourceNames:
          - privileged
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - "*"
          resourceNames:
          - extension-apiserver-authentication
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          - clusterrolebindings
          - roles
          - rolebindings
          verbs:
          - watch
          - list
          - get
          - create
          - delete
          - patch
          - update
        - apiGroups:
          - ""
          resources:
          - serviceaccounts
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - list
          - create
          - watch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - "*"
        - apiGroups:
          - ""
          resources:
          - nodes
          verbs:
          - "*"
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
          - list
          - watch
          - create
          - patch
          - delete
          - update
        - apiGroups:
          - ""
          resources:
          - persistentvolumes
          verbs:
          - create
          - delete
          - list
          - get
          - watch
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - persistentvolumeclaims
          verbs:
          - get
          - list
          - watch
          - update
        - apiGroups:
          - ""
          resources:
          - "persistentvolumeclaims/status"
          verbs:
          - patch
          - update
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - "*"
        - apiGroups:
          - storage.k8s.io
          resources:
          - volumeattachments
          verbs:
          - get
          - list
          - watch
          - update
          - delete
          - create
          - patch
        - apiGroups:
          - snapshot.storage.k8s.io
          resources:
          - volumesnapshotcontents/status
          verbs:
          - update
          - patch
        - apiGroups:
          - storage.k8s.io
          resources:
          - storageclasses
          - csinodes
          verbs:
          - create
          - get
          - list
          - watch
          - update
          - delete
        - apiGroups:
          - "*"
          resources:
          - events
          verbs:
          - get
          - patch
          - create
          - list
          - watch
          - update
          - delete
        - apiGroups:
          - snapshot.storage.k8s.io
          resources:
          - volumesnapshotclasses
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - delete
        - apiGroups:
          - snapshot.storage.k8s.io
          resources:
          - volumesnapshotcontents
          verbs:
          - create
          - get
          - list
          - watch
          - update
          - delete
        - apiGroups:
          - snapshot.storage.k8s.io
          resources:
          - volumesnapshots
          verbs:
          - get
          - list
          - watch
          - update
        - apiGroups:
          - storage.k8s.io
          resources:
          - csidrivers
          verbs:
          - create
          - get
          - list
          - watch
          - update
          - delete
        - apiGroups:
          - ebs.aws.csi.openshift.io
          resources:
          - "*"
          verbs:
          - "*"
        - apiGroups:
          - cloudcredential.openshift.io
          resources:
          - credentialsrequests
          verbs:
          - "*"
      deployments:
      - name: aws-ebs-csi-driver-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: aws-ebs-csi-driver-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: aws-ebs-csi-driver-operator
            spec:
              priorityClassName: system-cluster-critical
              serviceAccountName: aws-ebs-csi-driver-operator
              tolerations:
              - key: CriticalAddonsOnly
                operator: Exists
              containers:
              - name: aws-ebs-csi-driver-operator
                image: quay.io/openshift/origin-aws-ebs-csi-driver-operator:latest
                imagePullPolicy: Always
                args:
                - start
                env:
                - name: OPERATOR_IMAGE_VERSION
                  value: "0.0.1"
                - name: OPERAND_IMAGE_VERSION
                  value: "0.0.1"
                - name: DRIVER_IMAGE
                  value: quay.io/openshift/origin-aws-ebs-csi-driver:latest
                - name: PROVISIONER_IMAGE
                  value: quay.io/openshift/origin-csi-external-provisioner:latest
                - name: ATTACHER_IMAGE
                  value: quay.io/openshift/origin-csi-external-attacher:latest
                - name: RESIZER_IMAGE
                  value: quay.io/openshift/origin-csi-external-resizer:latest
                - name: SNAPSHOTTER_IMAGE
                  value: quay.io/openshift/origin-csi-external-snapshotter:latest
                - name: NODE_DRIVER_REGISTRAR_IMAGE
                  value: quay.io/openshift/origin-csi-node-driver-registrar:latest
                - name: LIVENESS_PROBE_IMAGE
                  value: quay.io/openshift/origin-csi-livenessprobe:latest
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: aws-ebs-csi-driver-operator

  customresourcedefinitions:
    owned:
    - kind: Driver
      displayName: EBS CSI Driver
      group: ebs.aws.csi.openshift.io
      name: drivers.ebs.aws.csi.openshift.io
      description: Manage EBS CSI driver for OpenShift
      version: v1alpha1
      specDescriptors:
        - description: Management state of operator
          displayName: Managementstate
          path: managementState
        - description: Log level of operator
          displayName: LogLevel
          path: logLevel
      statusDescriptors:
        - description: Last generation of this object
          displayName: ObservedGeneration
          path: observedGeneration
        - description: Last known condition of the operator
          displayName: Conditions
          path: conditions
          x-descriptors:
            - 'urn:alm:descriptor:io.kubernetes.conditions'
