kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aws-ebs-csi-driver-operator-role
subjects:
  - kind: ServiceAccount
    name: aws-ebs-csi-driver-operator
    namespace: openshift-aws-ebs-csi-driver-operator
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
